apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 30005
  #type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template: 
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: simple-app
          image: seif/kubernetes-day
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001


